# Copyright 2020 Tata Elxsi canonical@tataelxsi.onmicrosoft.com
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
---
options:
    ssh_port:
        type: int
        description: 'ssh_port is used for
                       communication between ran and core'
        default: 22
