#!/bin/sh

msin=`action-get msin`
mcc=`action-get mcc`
mnc=`action-get mnc`
routingindicator=`action-get routingindicator`
protectionscheme=`action-get protectionscheme`
k=`action-get k`
opc=`action-get opc`
uemgmtip=`action-get uemgmtip`
pdusessionid1=`action-get pdusessionid1`
datanetworkname1=`action-get datanetworkname1`
uepdumacaddress1=`action-get uepdumacaddress1`
sst1=`action-get sst1`
sd1=`action-get sd1`




curl --location --request POST 'http://localhost:8081/ueconfigread' \
--header 'Content-Type: application/json' \
--header 'cart-id: 9' \
--data-raw "{
\"Datas\": [
       {
          \"msin\": \"$msin\",
          \"mcc\": $mcc,
          \"mnc\": $mnc,
          \"routingindicator\": \"$routingindicator\",
          \"protectionscheme\": \"$protectionscheme\",
          \"authparam\":

           { \"k\": $k, \"opc\": $opc }
           ,
          \"uemgmtip\": \"$uemgmtip\",
          \"pdusessions\": [
	           {
                           \"pdusessionid\": $pdusessionid1,
                           \"datanetworkname\": \"$datanetworkname1\",
                           \"uEPDUMacAddress\": \"$uepdumacaddress1\",
                           \"snssai\":

                               { \"sst\": $sst1, \"sd\": \"$sd1\" }
                   }
         ]
       }
   ]
}"
