#!/bin/sh
# Copyright 2020 Tata Elxsi
#
# Licensed under the Apache License, Version 2.0 (the License); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# For those usages not covered by the Apache License, Version 2.0 please
# contact: canonical@tataelxsi.onmicrosoft.com
#
# To get in touch with the maintainers, please contact:
# canonical@tataelxsi.onmicrosoft.com
##


msin=`action-get msin`
mcc=`action-get mcc`
mnc=`action-get mnc`
routingindicator=`action-get routing-indicator`
protectionscheme=`action-get protection-scheme`
k=`action-get k`
opc=`action-get opc`
uemgmtip=`action-get ue-mgmt-ip`
pdusessionid1=`action-get pdu-session-id`
datanetworkname1=`action-get data-network-name`
uepdumacaddress1=`action-get ue-pdu-macaddress`
sst1=`action-get sst`
sd1=`action-get sd`




curl --location --request POST 'http://localhost:8081/ueconfigread' \
--header 'Content-Type: application/json' \
--header 'cart-id: 9' \
--data-raw "{
\"Datas\": [
       {
          \"msin\": \"$msin\",
          \"mcc\": $mcc,
          \"mnc\": $mnc,
          \"routingindicator\": \"$routingindicator\",
          \"protectionscheme\": \"$protectionscheme\",
          \"authparam\":

           { \"k\": $k, \"opc\": $opc }
           ,
          \"uemgmtip\": \"$uemgmtip\",
          \"pdusessions\": [
	           {
                           \"pdusessionid\": $pdusessionid1,
                           \"datanetworkname\": \"$datanetworkname1\",
                           \"uEPDUMacAddress\": \"$uepdumacaddress1\",
                           \"snssai\":

                               { \"sst\": $sst1, \"sd\": \"$sd1\" }
                   }
         ]
       }
   ]
}"
